### ISSUE TITLE
Add conn.getMetaData().getFunction() test to stock_jdbc

### ISSUE THREAD

**Issue by marregui** [crate/crate-qa#158]
In relation to issue https://github.com/crate/crate/issues/9976 this test will check that `conn.getMetaData().getFunction()` returns information. In particular this code should work and display all available system and user defined functions for both CrateDB and postgres:

```
        Properties props = new Properties();
        props.put("user", "crate");
        props.put("password", "");
        try (Connection conn = DriverManager.getConnection("jdbc:postgresql://localhost:5432/", props)) {
            DatabaseMetaData meta = conn.getMetaData();
            ResultSet function = meta.getFunctions(null, null, null);
            while (function.next()) {
                String schema = function.getString(2);
                String name = function.getString(3);
            }
        }
```

**Comment by mfussenegger** [comment]
There is already a test case that will need to be adapted once `pg_get_function_result` is available:

https://github.com/crate/crate-qa/blob/cd8c0e4b4c64ca9128e8f1623e9c23fd7b0ea788/tests/client_tests/stock_jdbc/src/test/java/stock_jdbc/JdbcMetaDataTest.java#L222-L231
