### ISSUE TITLE
Add rolling-upgrade test to ingest data while upgrading and running a mixed cluster

### ISSUE THREAD

**Issue by seut** [crate/crate-qa#271]
We must ensure that ingestion is still fully working while running a mixed version cluster in a rolling upgrade scenario.
Same for queries against recent ingested data (e.g. PK lookups, or using intermediate `refresh`).
To reflect production use-case, the test should issue large concurrent inserts/upserts instead of inserting just a couple of rows.

This should highlight possible issues popping up by changes inside our write code components (which unfortunately happened recently while no tests failed and such we weren't aware of).

**Comment by mkleen** [comment]
> `COPY FROM` is also related to
> 
> > the test should issue large concurrent inserts/
> 
> `COPY FROM `will be updated ([crate/crate#14019](https://github.com/crate/crate/issues/14019)) and there will be some BWC code. Post 5.5.0 versions will take a different plan.

Can you move this into an own issue?

**Comment by seut** [comment]
Outcome of an internal discussion:

- Let's change the existing `bwc.rolling_upgrade` test to not always wait for the shard to be active before running the test statements like inserts, but do this randomly. Ensure random tests can be repeated in case of a failure (seeds).
- Optional: to speed up this test suite, also randomize the upgrade path to *not* go through the all versions but only to some of them (at least 2 versions of course ;).

**Comment by seut** [comment]
We already cover the case of concurrent indexing while a node is restarting within `crate/crate` by `ClusterDisruptionIT.testRestartNodeWhileIndexing` and `DiskDisruptionIT.testGlobalCheckpointIsSafe`.

What is missing at the `rolling_upgrade` tests is:

-  [ ] ensure that writes into normal tables are successful while running a mixed version cluster (we already do this with partitioned tables).
